export interface PendingSalaryRecord {
  id: string;
  name: string;
  uploadedBy: string;
  avatar: string;
  salon: string;
  salonLogo: string;
  period: string;
  gross: number;
  net: number;
  status: "Pending" | "Declined";
  uploadedDate: string;
}

export const pendingSalariesData: PendingSalaryRecord[] = [
  {
    id: "1",
    name: "Maria Rodriguez",
    uploadedBy: "Maria Rossi",
    avatar: "/avatar/avatar.png",
    salon: "Glamour Beauty",
    salonLogo: "/RecentActivity/RecentActivity1.png",
    period: "December 2024",
    gross: 4200,
    net: 3200,
    status: "Declined",
    uploadedDate: "Dec 01, 2024",
  },
  {
    id: "2",
    name: "Maria Rodriguez",
    uploadedBy: "Maria Rossi",
    avatar: "/avatar/avatar1.png",
    salon: "Style Studio",
    salonLogo: "/RecentActivity/RecentActivity2.png",
    period: "December 2024",
    gross: 4200,
    net: 3200,
    status: "Declined",
    uploadedDate: "Dec 01, 2024",
  },
  {
    id: "3",
    name: "Maria Rodriguez",
    uploadedBy: "Maria Rossi",
    avatar: "/avatar/avatar2.png",
    salon: "Style Studio",
    salonLogo: "/RecentActivity/RecentActivity1.png",
    period: "December 2024",
    gross: 4200,
    net: 3200,
    status: "Declined",
    uploadedDate: "Dec 01, 2024",
  },
  {
    id: "4",
    name: "Maria Rodriguez",
    uploadedBy: "Maria Rossi",
    avatar: "/avatar/avatar3.png",
    salon: "Chic Hair & Beauty",
    salonLogo: "/RecentActivity/RecentActivity2.png",
    period: "December 2024",
    gross: 4200,
    net: 3200,
    status: "Pending",
    uploadedDate: "Dec 01, 2024",
  },
  {
    id: "5",
    name: "Maria Rodriguez",
    uploadedBy: "Maria Rossi",
    avatar: "/avatar/avatar.png",
    salon: "Chic Hair & Beauty",
    salonLogo: "/RecentActivity/RecentActivity1.png",
    period: "December 2024",
    gross: 4200,
    net: 3200,
    status: "Pending",
    uploadedDate: "Dec 01, 2024",
  },
  {
    id: "6",
    name: "Maria Rodriguez",
    uploadedBy: "Maria Rossi",
    avatar: "/avatar/avatar1.png",
    salon: "Style Studio",
    salonLogo: "/RecentActivity/RecentActivity2.png",
    period: "December 2024",
    gross: 4200,
    net: 3200,
    status: "Pending",
    uploadedDate: "Dec 01, 2024",
  },
  {
    id: "7",
    name: "Jane Smith",
    uploadedBy: "Alice Johnson",
    avatar: "/avatar/avatar2.png",
    salon: "Glamour Beauty",
    salonLogo: "/RecentActivity/RecentActivity1.png",
    period: "December 2024",
    gross: 3800,
    net: 2900,
    status: "Declined",
    uploadedDate: "Dec 02, 2024",
  },
  {
    id: "8",
    name: "Emma Davis",
    uploadedBy: "Alice Johnson",
    avatar: "/avatar/avatar3.png",
    salon: "Style Studio",
    salonLogo: "/RecentActivity/RecentActivity2.png",
    period: "December 2024",
    gross: 4500,
    net: 3400,
    status: "Pending",
    uploadedDate: "Dec 03, 2024",
  },
  {
    id: "9",
    name: "Oliver Twist",
    uploadedBy: "John Doe",
    avatar: "/avatar/avatar.png",
    salon: "Chic Hair & Beauty",
    salonLogo: "/RecentActivity/RecentActivity1.png",
    period: "December 2024",
    gross: 3950,
    net: 3100,
    status: "Declined",
    uploadedDate: "Dec 04, 2024",
  },
  {
    id: "10",
    name: "Sophia Martinez",
    uploadedBy: "John Doe",
    avatar: "/avatar/avatar1.png",
    salon: "Glamour Beauty",
    salonLogo: "/RecentActivity/RecentActivity2.png",
    period: "December 2024",
    gross: 4100,
    net: 3150,
    status: "Pending",
    uploadedDate: "Dec 05, 2024",
  },
];
